### ISSUE TITLE
Uncaught exception if !conv 1 grlc euro

### ISSUE THREAD

**Issue by JasonG-FR** [GarlicoinForum/GoldenBot#7]
Somehow euro is detected as a valid currency when it shouldn't (eur is the correct currency).

Traceback : 
```
Ignoring exception in on_message
Traceback (most recent call last):
  File "/home/gordane/.local/lib/python3.5/site-packages/discord/client.py", line 307, in _run_event
    yield from getattr(self, event)(*args, **kwargs)
  File "goldenbot.py", line 242, in on_message
    await convert_3(client, message, msg)
  File "goldenbot.py", line 121, in convert_3
    rate = await get_rate_crypto(client, message, crypto, fiat)
  File "goldenbot.py", line 172, in get_rate_crypto
    return float(datas["price_{}".format(fiat.lower())])
KeyError: 'price_euro'
Traceback (most recent call last):
  File "goldenbot.py", line 327, in <module>
    main()
  File "goldenbot.py", line 321, in main
    client.run(BOT_TOKEN) 
  File "/home/gordane/.local/lib/python3.5/site-packages/discord/client.py", line 519, in run
    self.loop.run_until_complete(self.start(*args, **kwargs))
  File "/usr/lib/python3.5/asyncio/base_events.py", line 364, in run_until_complete
    self._check_closed()  
  File "/usr/lib/python3.5/asyncio/base_events.py", line 334, in _check_closed
    raise RuntimeError('Event loop is closed')
RuntimeError: Event loop is closed
Unclosed client session   
client_session: <aiohttp.client.ClientSession object at 0x7f582d82e470>
```

**Comment by trishmapow** [comment]
`datas.get("price_{}".format(fiat.lower()), None]` in line 172

**Comment by JasonG-FR** [comment]
Found the bug :
```python
curr1 = "GRLC"
curr2 = "EURO"
is_crypto(curr1) or is_fiat(curr1) and is_crypto(curr2) or is_fiat(curr2)
>>> True
```
I forgot the parenthesis : 
```python
curr1 = "GRLC"
curr2 = "EURO"
(is_crypto(curr1) or is_fiat(curr1)) and (is_crypto(curr2) or is_fiat(curr2))
>>> False
```
